Onlinico.MiPoint.Web.Api/Controllers/MerchantController.cs
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Http;
using System.Web.Http.Results;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Onlinico.MiPoint.Web.Api.Hubs.Interfaces;
using Onlinico.MiPoint.Web.Api.Models.Web;
using Onlinico.MiPoint.Web.Api.Models.Web.Mapper;
using Onlinico.MiPoint.Web.Api.Models.Web.Validation;
using Onlinico.MiPoint.Web.Service.Interfaces.Global.External;
using Onlinico.MiPoint.Web.Service.Interfaces.Web;
using Onlinico.MiPoint.Web.Service.Mapper.Global.Omnivore;

namespace Onlinico.MiPoint.Web.Api.Controllers
{
    /// <summary>
    /// Merchant Controller
    /// </summary>
    public class MerchantController : BaseController
    {
        private readonly IMerchantService _merchantService;
        private readonly IOmnivoreService _omnivoreService;
        private readonly ILocationService _locationService;
        private readonly IAgentHubPusher _agentHubPusher;

        /// <summary>
        /// Dependency Injection
        /// </summary>
        /// <param name="merchantService">Inject Merchant service</param>
        /// <param name="omnivoreService">Inject Omnivore service</param>
        /// <param name="locationService">Inject Location Service</param>
        /// <param name="agentHubPusher">Inject agent hub pusher</param>
        /// <param name="configuration">Inject Omnivore service</param>
        public MerchantController(IMerchantService merchantService, IOmnivoreService omnivoreService, ILocationService locationService, IAgentHubPusher agentHubPusher, Core.Interfaces.IConfiguration configuration) : base(configuration)
        {
            _merchantService = merchantService;
            _omnivoreService = omnivoreService;
            _locationService = locationService;
            _agentHubPusher = agentHubPusher;
        }

        /// <summary>
        /// Merchants page
        /// </summary>
        /// <returns>View</returns>
        public ActionResult Index()
        {
            ViewBag.IsAdmin = IsAdmin;

            return View();
        }

        /// <summary>
        /// Merchants partial page
        /// </summary>
        /// <returns>Partial View</returns>
        public ActionResult Merchants()
        {
            ViewBag.IsAdmin = IsAdmin;
            return View();
        }

        /// <summary>
        /// Get merchant datatable rows
        /// </summary>
        /// <returns></returns>
        public ActionResult MerchantRows()
        {
            ViewBag.IsAdmin = IsAdmin;

            var merchantsResult = IsAdmin
                ? _merchantService.Get()
                : _merchantService.GetForUser(User.Identity.GetUserId());

            return View(merchantsResult.Object?.ToMerchantViewModels());
        }

        /// <summary>
        /// Merchant partial page
        /// </summary>
        /// <param name="merchantId">Merchant id</param>
        /// <returns>Partial View</returns>
        public async Task<ActionResult> Users(Guid merchantId)
        {
            ViewBag.MerchantId = merchantId;
            var result = await _merchantService.GetUsersAsync(merchantId);
            return View(result.Object?.ToUserViewModelList());
        }
        
        [System.Web.Mvc.HttpGet]
        public async Task<ActionResult> MerchantForm()
        {
            var resultModel = new MerchantModel();

            var omnivoreProdLocationsResult = await _omnivoreService.GetLocationsByApiKey(Configuration.OmnivoreProdApiKey);
            var omnivoreDevLocationsResult = await _omnivoreService.GetLocationsByApiKey(Configuration.OmnivoreDevApiKey);
            if (omnivoreProdLocationsResult.Succeed)
            {
                if (omnivoreDevLocationsResult.Succeed && omnivoreDevLocationsResult.Object != null && omnivoreDevLocationsResult.Object.Any())
                {
                    omnivoreProdLocationsResult.Object.AddRange(omnivoreDevLocationsResult.Object);
                }

                var allLocations = omnivoreProdLocationsResult.Object.ToDomainLocations();

                var existLocationsResult = await _locationService.GetAsync();
                if (existLocationsResult.Succeed)
                {
                    var existinLocations = existLocationsResult.Object.Select(l => l.Identifier).ToList();

                    var locations = allLocations.Where(
                        l => existinLocations.All(ml => ml != l.Identifier)).ToList();

                    resultModel.SelectedLocations = locations.ToLocationViewModelList().ToSelectedItems();
                }
            }

            return View(resultModel);
        }

        /// <summary>
        /// Add new Merchant
        /// </summary>
        /// <param name="model">Merchant model</param>
        /// <param name="timeOffset">client time offset</param>
        /// <returns></returns>
        [System.Web.Mvc.HttpPost]
        public async Task<ActionResult> MerchantForm(MerchantModel model, [FromUri]int timeOffset = 0)
        {
            if (ModelState.IsValid)
            {
                var queue = new ConcurrentQueue<Domain.Models.Global.Omnivore.LocationModel>();

                if (model.Identifiers != null && model.Identifiers.Any())
                {
                    Task.WaitAll(model.Identifiers.Select(i =>
                    {
                        return _omnivoreService.GetLocationAsync(Configuration.OmnivoreProdApiKey, i, true).ContinueWith(
                            locationResult =>
                            {
                                if (locationResult.Result.Succeed && locationResult.Result.Object != null)
                                {
                                    queue.Enqueue(locationResult.Result.Object);
                                }
                                else
                                {
                                    var devLocationResult = _omnivoreService.GetLocationAsync(Configuration.OmnivoreDevApiKey, i, true).Result;
                                    if (devLocationResult.Succeed && devLocationResult.Object != null)
                                    {
                                        queue.Enqueue(devLocationResult.Object);
                                    }
                                }
                            });
                    }).ToArray());
                }
                
                string userId = null;
                if (!IsAdmin)
                {
                    userId = User.Identity.GetUserId();
                }
                var result = await _merchantService.AddAsync(model.ToDomainMerchantModel(), queue.ToList().ToDomainLocations(), userId, timeOffset);
                if (result.Succeed)
                {
                    var inviteController = DependencyResolver.Current.GetService<InviteController>();
                    inviteController.ControllerContext = ControllerContext;
                    try
                    {
                        await inviteController.InviteUser(new InviteModel
                        {
                            Email = result.Object.Email,
                            MerchantId = result.Object.Id
                        });
                    }
                    catch (Exception ex)
                    {
                        var testt = ex.Message;
                    }
                    

                    return PartialView("MerchantRow", result.Object?.ToMerchantViewModel());
                }
                else
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest, result.Error);
                }

            }
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Invalid data.");
        }

        /// <summary>
        /// Get edit merchant info page
        /// </summary>
        /// <param name="merchantId">merchant id</param>
        /// <returns></returns>
        [System.Web.Mvc.HttpGet]
        public ActionResult EditMerchant(Guid merchantId)
        {
            var merchantResult = _merchantService.Get(merchantId);

            if (merchantResult.Succeed)
            {
                return View(merchantResult.Object?.ToMerchantViewModel());
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, merchantResult.Error);
            }
        }

        /// <summary>
        /// Post edit merchant info
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [System.Web.Mvc.HttpPost]
        public async Task<ActionResult> EditMerchant(MerchantModel model)
        {
            var updateResult = _merchantService.Update(model.ToDomainMerchantModel());
            if (updateResult.Succeed)
            {
                ViewBag.IsAdmin = IsAdmin;

                _agentHubPusher.SendClientSettingsByMerchant(model.Id);
                return PartialView("MerchantRow", updateResult.Object?.ToMerchantViewModel());
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, updateResult.Error);
            }
        }

        /// <summary>
        /// Remove Merchant
        /// </summary>
        /// <param name="id">Merchant id</param>
        /// <returns></returns>
        [System.Web.Mvc.HttpDelete]
        public async Task<ActionResult> RemoveMerchant(Guid id)
        {
            var result = await _merchantService.RemoveAsync(id);
            return Json(result.Succeed, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Unlink user from merchant
        /// </summary>
        /// <param name="merchantId">Merchant id</param>
        /// <param name="userId">user id</param>
        /// <returns></returns>

Onlinico.MiPoint.Web.Api/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Onlinico.MiPoint.Web.Api.Models.Web;
using Onlinico.MiPoint.Web.Api.Models.Web.Mapper;
using Onlinico.MiPoint.Web.Api.Models.Web.Validation;
using Onlinico.MiPoint.Web.Data.DataModel;
using Onlinico.MiPoint.Web.Service.Interfaces.Web;

namespace Onlinico.MiPoint.Web.Api.Controllers
{
    /// <summary>
    /// User controller
    /// </summary>
    [Authorize(Roles = "Admin")]
    public class UserController : BaseController
    {
        private readonly IUserService _userService;
        private readonly IMerchantService _merchantService;
        private readonly ApplicationUserManager _applicationUserManager;

        /// <summary>
        /// User controller constructor
        /// </summary>
        /// <param name="userService">Inject user service</param>
        /// <param name="merchantService">Inject merchant service</param>
        /// <param name="configuration">Inject configuration</param>
        /// <param name="applicationUserManager">Inject userManager</param>
        public UserController(IUserService userService, IMerchantService merchantService, Core.Interfaces.IConfiguration configuration, ApplicationUserManager applicationUserManager) : base(configuration)
        {
            _userService = userService;
            _merchantService = merchantService;
            _applicationUserManager = applicationUserManager;
        }

        /// <summary>
        /// Index view
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Users()
        {
            return View();
        }

        public ActionResult UserRows()
        {
            return View(_userService.Get()?.ToUserViewModelList());
        }

        [HttpGet]
        public ActionResult UserRelations(string userId)
        {
            ViewBag.UserId = userId;

            var result = new UserMerchantRelationsModel { UserId = userId };

            var allMerchantsResult = _merchantService.Get();
            if (allMerchantsResult.Succeed)
            {
                var userMerchantResult = _userService.GetMerchants(userId);
                result.SelectedMerchantItems = userMerchantResult.Succeed 
                    ? allMerchantsResult.Object?.ToMerchantViewModels().ToSelectedItems(userMerchantResult.Object?.ToMerchantViewModels()) 
                    : allMerchantsResult.Object?.ToMerchantViewModels().ToSelectedItems();
            }

            return View(result);
        }

        [HttpPost]
        public ActionResult UserRelations(UserMerchantRelationsModel model)
        {
            var result = _userService.UpdateUserRelations(model.UserId, model.SelectedMerchants);
            return new HttpStatusCodeResult(result.Succeed ? HttpStatusCode.OK : HttpStatusCode.BadRequest);
        }

        public JsonResult RemoveUser(string userId)
        {
            var result = false;
            var user = _applicationUserManager.FindById(userId);
            if (user != null)
            {
                result = _merchantService.RemoveMerchantsFromUser(userId).Succeed;
                if (result)
                {
                    result = _applicationUserManager.Delete(user).Succeeded;
                }
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Register()
        {
            var allMerchantsResult = _merchantService.Get();
            if (allMerchantsResult.Succeed)
            {
                var result = new RegisterModel()
                {
                    SelectedMerchantItems = allMerchantsResult.Object?.ToMerchantViewModels().ToSelectedItems()
                };
                return View(result);
            }
            return View("Error");
        }

        [HttpPost]
        public async Task<ActionResult> Register(RegisterModel model)
        {
            if (model.IsValid())
            {
                var createResult = await _applicationUserManager.CreateAsync(new User { UserName = model.Login, FullName = model.Name, Email = model.Login }, model.Password);
                if (createResult.Succeeded)
                {
                    var user = await _applicationUserManager.FindByNameAsync(model.Login);
                    if (user != null)
                    {
                        await _applicationUserManager.AddToRoleAsync(user.Id, Configuration.MerchantManagerRole);

                        if (model.SelectedMerchants != null && model.SelectedMerchants.Any())
                        {
                            var result = _merchantService.RelateMerchantsWithUser(model.SelectedMerchants, user.Id);
                            if (!result.Succeed)
                            {
                                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "User was created, but not related with retailers.");
                            }
                        }

                        return PartialView("UserRow", user?.ToUserModel());
                    }
                    else
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Some error happened, please try again later.");
                    }
                }
                else
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest, createResult.Errors.First().Replace("Name", "Login"));
                }
            }
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Invalid user data.");
        }

        public JsonResult IsUsernameUnique(string login)
        {
            var result = _userService.IsUsernameUnique(login);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

Onlinico.MiPoint.Web.Api/Views/Merchant/EditMerchant.cshtml
@model Onlinico.MiPoint.Web.Api.Models.Web.MerchantModel
@{
    Layout = null;
}
@if (Model != null)
{
    <div class="modal-dialog" style="width: 650px">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Edit Merchant</h4>
            </div>

            @using (Ajax.BeginForm("EditMerchant", "Merchant", new AjaxOptions { HttpMethod = "POST", OnSuccess = "AddMerchantSuccess", OnBegin = "AddMerchantBegin", OnFailure = "AddMerchantFailre", OnComplete = "AddMerchantComplete" }, new { id = "merchant-form" }))
            {
                <div class="modal-body">
                    <div>
                        <div>
                            <input name="model.Id" value="@Model.Id" type="hidden" />

                            <input name="model.Name" value="@Model.Name" required type="text" class="inputs modal-dialog-input" maxlength="250" placeholder="Name" />

                            <input name="model.Email" value="@Model.Email" required type="email" pattern="[a-z0-9._%+-]+@("@")[a-z0-9.-]+\.[a-z]{2,63}$" title="Invalid email format." maxlength="250" class="inputs modal-dialog-input" placeholder="Email address" />

                            <input name="model.PhoneNumber" value="@Model.PhoneNumber" type="tel" pattern="(\+?\d[- .]*){7,13}" title="International, national or local telephone number" class="inputs modal-dialog-input" placeholder="Phone number" />

                            <input name="model.Country" value="@Model.Country" type="text" pattern="[A-Za-z\s]+" title="Only letters" maxlength="250" class="inputs modal-dialog-input" placeholder="Country" />

                            <input name="model.Zip" value="@Model.Zip" type="number" max="99999" min="0" class="inputs modal-dialog-input" placeholder="Zip code" />

                            <input name="model.State" value="@Model.State" pattern="[A-Za-z\s]+" title="Only letters" type="text" maxlength="250" class="inputs modal-dialog-input" placeholder="State" />

                            <input name="model.City" value="@Model.City" type="text" pattern="[A-Za-z\s]+" title="Only letters" maxlength="250" class="inputs modal-dialog-input" placeholder="City" />

                            <input name="model.Address" value="@Model.Address" type="text" maxlength="250" class="inputs modal-dialog-input" placeholder="Address" />

                            <input name="model.WebSite" value="@Model.WebSite" type="text" maxlength="250" class="inputs modal-dialog-input" placeholder="Website" />

                            <input name="model.LogoUrl" value="@Model.LogoUrl" type="text" maxlength="250" class="inputs modal-dialog-input" placeholder="Logo Url" />
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <input class="btn btn-default button save-button" type="submit" value="Save" />
                    <button type="button" class="btn btn-default button back-button" data-dismiss="modal">Cancel</button>
                </div>
            }
        </div>
    </div>

    <script type="text/javascript">
        $(function () {
            $("#merchant-form").attr("action", $("#merchant-form").attr("action") + "&timeOffset=" + new Date().getTimezoneOffset());
        });

        function AddMerchantBegin() {
            window.ShowOwerlay();
        }

        function AddMerchantSuccess(result) {

            /*remove old row*/
            table.row($('#' + '@Model.Id')).remove().draw();

            /*add new row*/
            var rowDraw = table.row.add($(result)[0]).draw();
            rowDraw.show().draw(false);
            var rowNode = rowDraw.node();
            var row = $(rowNode);
            row.addClass('active').siblings().removeClass('active');
            row.click(function () {
                $(this).addClass('active').siblings().removeClass('active');
            });

            /*hide model*/
            $('#merchant-info-form-container').modal('hide');

            $("#merchantName, #omnivoreApiKey").val("");
            window.Notify('<strong>Success.</strong>', "Update merrchant.", 'success');
        }

        function AddMerchantFailre(result) {
            window.Notify('<strong>Error.</strong>', result.statusText, 'danger');
        }

        function AddMerchantComplete(result) {
            window.HideOwerlay();
        }
    </script>
}
else
{
    <header style="margin: 15px">
        <h3 style="color: #2c3e50;">Some error happened, please try later</h3>
    </header>
}
<style>
    input::-webkit-outer-spin-button, input::-webkit-inner-spin-button {
        /* display: none; <- Crashes Chrome on hover */
        -webkit-appearance: none;
        margin: 0; /* <-- Apparently some margin are still there even though it's hidden */
    }
</style>

Onlinico.MiPoint.Web.Api/Views/Merchant/Index.cshtml
<div>
    <header class="header">
        <h3>Merchants</h3>
        @if (ViewBag.IsAdmin ?? false)
        {
            <div style="float: right">
                <a onclick="ShowMerchantFormm()" class="action-btn action-btn-add" title="Add merchant"></a>
            </div>
        }
    </header>
    <div style="margin: 10px;">
        <div>
            @{ Html.RenderAction("Merchants", "Merchant"); }
        </div>
    </div>

    <div class="container">
        <div id="merchant-info-form-container" class="modal fade" role="dialog">

        </div>
    </div>

</div>

@section scripts {
    <script>

        function ShowMerchantFormm() {
            window.ShowOwerlay();
            var formContainer = $('#merchant-info-form-container');
            formContainer.load('@Url.Action("MerchantForm", "Merchant")');
            formContainer.modal('show');
            window.HideOwerlay();
        }
        
    </script>
}

Onlinico.MiPoint.Web.Api/Views/Merchant/MerchantForm.cshtml
@model Onlinico.MiPoint.Web.Api.Models.Web.MerchantModel
@{
    Layout = null;
}

@if (Model != null)
{
    <div class="modal-dialog" style="width: 650px">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Add Merchant</h4>
            </div>

            @using (Ajax.BeginForm("MerchantForm", "Merchant", new AjaxOptions { OnSuccess = "AddMerchantSuccess", OnBegin = "AddMerchantBegin", OnFailure = "AddMerchantFailre", OnComplete = "AddMerchantComplete" }, new { id = "merchant-form" }))
            {
                <div class="modal-body">
                    <div>
                        <div>

                            <input name="model.Name" required type="text" class="inputs modal-dialog-input" maxlength="250" placeholder="Name" />

                            <input name="model.Email" required type="email" pattern="[a-z0-9._%+-]+@("@")[a-z0-9.-]+\.[a-z]{2,63}$" title="Invalid email format." maxlength="250" class="inputs modal-dialog-input" placeholder="Email address" />

                            <input name="model.PhoneNumber" type="tel" pattern="(\+?\d[- .]*){7,13}" title="International, national or local telephone number" class="inputs modal-dialog-input" placeholder="Phone number" />

                            <input name="model.Country" type="text" maxlength="250" pattern="[A-Za-z\s]+" title="Only letters" class="inputs modal-dialog-input" placeholder="Country" />

                            <input name="model.Zip" type="number" max="99999" min="0" class="inputs modal-dialog-input" placeholder="Zip code" />

                            <input name="model.State" type="text" maxlength="250" pattern="[A-Za-z\s]+" title="Only letters" class="inputs modal-dialog-input" placeholder="State" />

                            <input name="model.City" type="text" maxlength="250" pattern="[A-Za-z\s]+" title="Only letters" class="inputs modal-dialog-input" placeholder="City" />

                            <input name="model.Address" type="text" maxlength="250" class="inputs modal-dialog-input" placeholder="Address"/>

                            <input name="model.WebSite" type="text" maxlength="250" class="inputs modal-dialog-input" placeholder="Website"/>

                            <input name="model.LogoUrl" type="text" maxlength="250" class="inputs modal-dialog-input" placeholder="Logo Url" />
                        </div>
                        <div>
                            <select id="location-multiselect" name="model.Identifiers" multiple="multiple">
                                @if (Model != null && Model.SelectedLocations.Any())
                                {
                                    for (var i = 0; i < Model.SelectedLocations.Count; i++)
                                    {
                                        <option name="model.Identifiers[@i]" value="@Model.SelectedLocations[i].Item.Identifier" @(Model.SelectedLocations[i].Selected ? "selected" : "")>@Model.SelectedLocations[i].Item.Name</option>
                                    }
                                }
                            </select>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <input class="btn btn-default button save-button" type="submit" value="Add" />
                    <button type="button" class="btn btn-default button back-button" data-dismiss="modal">Cancel</button>
                </div>
            }
        </div>
    </div>

    <script type="text/javascript">
        $(function () {
            $('#location-multiselect').multiselect({
                includeSelectAllOption: true,
                enableFiltering: true
            });

            $("#merchant-form").attr("action", $("#merchant-form").attr("action") + "&timeOffset=" + new Date().getTimezoneOffset());
        });

        function AddMerchantBegin() {
            $(".add-button").attr('disabled', 'disabled');
            window.ShowOwerlay();
        }

        function AddMerchantSuccess(result) {
            /*add new row*/
            var rowDraw = table.row.add($(result)[0]).draw();
            rowDraw.show().draw(false);
            var rowNode = rowDraw.node();
            var row = $(rowNode);
            row.addClass('active').siblings().removeClass('active');
            row.click(function () {
                $(this).addClass('active').siblings().removeClass('active');
            });

            /*hide model*/
            $('#merchant-info-form-container').modal('hide');

            $("#merchantName, #omnivoreApiKey").val("");
            window.Notify('<strong>Success.</strong>', "Add merrchant.", 'success');

            window.Notify('<strong>Important.</strong>', "Now for work, you need configure your location settings. Follow in this Merchant locations, and then click settings", 'warning', 10000);
        }

        function AddMerchantFailre(result) {
            window.Notify('<strong>Error.</strong>', result.statusText, 'danger');
        }

        function AddMerchantComplete(result) {
            $(".add-button").removeAttr('disabled');
            window.HideOwerlay();
            window.CheckEmpty();
        }
    </script>
}
else
{
    <header style="margin: 15px">
        <h3 style="color: #2c3e50;">Some error happened, please try later</h3>
    </header>
}
<style>
    input::-webkit-outer-spin-button, input::-webkit-inner-spin-button {
        /* display: none; <- Crashes Chrome on hover */
        -webkit-appearance: none;
        margin: 0; /* <-- Apparently some margin are still there even though it's hidden */
    }
</style>

Onlinico.MiPoint.Web.Api/Views/Merchant/MerchantRow.cshtml
@model Onlinico.MiPoint.Web.Api.Models.Web.MerchantModel
@{
    Layout = null;
}

@if (Model != null)
{
    <tr id="@Model.Id">
        <td>
            <div>
                <a onclick="EditMerchant('@Model.Id')" class="table-icon edit-merchant-icon" title="Edit Merchant"></a>
                <a onclick="GoToMerchantLocations('@Model.Id')" class="table-icon markers-merchant-icon" title="Merchant locations"></a>
                <a onclick="MerchantUsers('@Model.Id')" class="table-icon merchant-users-icon" title="Merchant users"></a>
                @if (ViewBag.IsAdmin ?? true)
                {
                    <a onclick="RemoveMerchantConfirm('@Model.Id')" class="table-icon remove-merchant-icon" title="Remove Merchant"></a>
                }
            </div>
        </td>
        <td>
            <div class="table-six-col-content hideOverflow" style="max-width: 250px;">
                @Model.Name
            </div>
        </td>
        <td>
            <div class="table-six-col-content hideOverflow" style="max-width: 150px;">
                @Model.Created
            </div>
        </td>
        <td>
            <div class="table-six-col-content hideOverflow" style="max-width: 130px;">
                @Model.Country
            </div>
        </td>
        <td>
            <div class="table-six-col-content hideOverflow" style="max-width: 130px;">
                @Model.City
            </div>
        </td>
        <td>
            <div class="table-six-col-content hideOverflow" style="max-width: 130px;">
                @Model.Address
            </div>
        </td>
    </tr>
}

Onlinico.MiPoint.Web.Api/Views/Merchant/MerchantRows.cshtml
@model List<Onlinico.MiPoint.Web.Api.Models.Web.MerchantModel>
@{
    Layout = null;
}
@if (Model != null && Model.Any())
{
    foreach (var merchant in Model)
    {
        Html.RenderPartial("MerchantRow", merchant);
    }
}

Onlinico.MiPoint.Web.Api/Views/Merchant/UserRow.cshtml
@model Onlinico.MiPoint.Web.Api.Models.Web.UserModel

@{
    Layout = null;
}

<div id="@Model.Id" class="merchant-user-row">
    <a onclick="UnlinkUser('@Model.Id')" class="table-icon unlink-icon" title="Remove User @Model.FullName"></a>
    <label>@Model.FullName</label>
    <label>@Model.Login</label>
</div>