Onlinico.MiPoint.Web.Api/Models/Web/PaymentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Onlinico.MiPoint.Web.Api.Models.Web
{
    public class PaymentViewModel
    {
        public string CardType { get; set; }

        public string TenderType { get; set; }

        public string LocationId { get; set; }

        public string Id { get; set; }

        public string DeviceId { get; set; }

        public string OrderId { get; set; }

        public string Type { get; set; }

        public string Status { get; set; }

        public string Amount { get; set; }

        public long Tip { get; set; }

        public long Tax { get; set; }

        public string EmployeeCode { get; set; }

        public string TableNumber { get; set; }

        public string Message { get; set; }

        public DateTime Created { get; set; }

        public PaymentTransactionViewModel Transaction { get; set; }

        public PaymentReceptInfoViewModel ReceptInfo { get; set; }

        public List<PaymentItemViewModel> Items { get; set; }
    }

    public class PaymentItemViewModel
    {
        public Guid Id { get; set; }

        public string ItemId { get; set; }

        public string Name { get; set; }

        public int Quantity { get; set; }

        public long Price { get; set; }
    }

    public class PaymentTransactionViewModel
    {
        public string TransactionId { get; set; }

        public DateTimeOffset Issued { get; set; }

        public string CardEntryType { get; set; }

        public string CardType { get; set; }

        public string Last4 { get; set; }

        public string ReferenceId { get; set; }

        public string AuthCode { get; set; }

        public string ApplicationId { get; set; }

        public string TransactionType { get; set; }

        public string Cvm { get; set; }
    }

    public class PaymentReceptInfoViewModel
    {
        public Guid Id { get; set; }

        public string OrderNumber { get; set; }

        public DateTimeOffset Issued { get; set; }

        public long OrderSubTotal { get; set; }

        public long OrderTax { get; set; }

        public long OrderTotal { get; set; }

        public long OrderServiceCharge { get; set; }

        public string Cashier { get; set; }

        public string LocationName { get; set; }

        public string ReceiptHeader1 { get; set; }

        public string ReceiptHeader2 { get; set; }

        public string PhoneNumber { get; set; }

        public string Website { get; set; }
    }
}

Onlinico.MiPoint.Web.Api/Controllers/Api/v3/PaymentController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;
using System.Web.Http.OData.Query;
using Newtonsoft.Json;
using Onlinico.MiPoint.Web.Api.Models.Api.v3;
using Onlinico.MiPoint.Web.Api.Models.Api.v3.Enums;
using Onlinico.MiPoint.Web.Api.Models.Api.v3.Mapper;
using Onlinico.MiPoint.Web.Core.Interfaces;
using Onlinico.MiPoint.Web.Logger.Interfaces;
using Onlinico.MiPoint.Web.Service.Interfaces.Api.v3;
using Onlinico.MiPoint.Web.Service.Interfaces.Global;
using Onlinico.MiPoint.Web.Service.Interfaces.Global.External;

namespace Onlinico.MiPoint.Web.Api.Controllers.Api.v3
{
    /// <summary>
    /// Payment controller
    /// </summary>
    [Attributes.Authorize, RoutePrefix("api/v3/payments")]
    public class PaymentController : BaseController
    {
        private readonly IPaymentService _paymentService;
        private readonly IOmnivoreService _omnivoreService;
        private readonly IAuthService _authService;

        /// <summary>
        /// Payment controller constructor
        /// </summary>
        /// <param name="paymentService">Inject payment service</param>
        /// <param name="omnivoreService">Inject omnivore service</param>
        /// <param name="authService">Inject auth service</param>
        /// <param name="logger">Inject logger service</param>
        /// <param name="configuration">Inject config</param>
        public PaymentController(IPaymentService paymentService, IOmnivoreService omnivoreService, IAuthService authService, ILogger logger, IConfiguration configuration) : base(logger, configuration)
        {
            _paymentService = paymentService;
            _omnivoreService = omnivoreService;
            _authService = authService;
        }

        /// <summary>
        /// Get payments(OData query v3 available)
        /// </summary>
        /// <param name="queryOptions">ODAta PaymentModel query options</param>
        /// <returns></returns>
        [HttpGet, Route("")]
        [ResponseType(typeof(List<PaymentModel>))]
        public async Task<IHttpActionResult> Get(ODataQueryOptions<PaymentModel> queryOptions)
        {
            var result = await _paymentService.GetByLocationAsync(LocationId);

            if (result.Succeed && result.Object != null)
            {
                try
                {
                    var payment = result.Object.ToApiPayments();

                    return Ok(queryOptions.ApplyTo(payment));
                }
                catch (Exception ex)
                {
                    return BadRequest(ex.Message);
                }
            }
            else
            {
                return BadRequest(result.Error);
            }
        }

        /// <summary>
        /// Add payment
        /// </summary>
        /// <param name="model">Payment model</param>
        /// <returns></returns>
        [HttpPost, Route("")]
        [ResponseType(typeof(CreateResultModel))]
        public async Task<IHttpActionResult> Post(PaymentModel model)
        {
            var result = new Domain.Models.Api.v3.ResultModel(false);

            if (ModelState.IsValid)
            {
                if (model.Type == PaymentTypeEnum.Normal)
                {
                    var identityResult = _authService.GetIdentity(LocationId);
                    if (identityResult.Succeed && identityResult.Object != null)
                    {
                        var ticketId = model?.OrderId?.Split('-').FirstOrDefault();
                        var omnivoreTicketResult = await _omnivoreService.GetTicketAsync(identityResult.Object.OmnivoreApiKey,
                                identityResult.Object.OmnivoreLocationId, ticketId);
                        if (omnivoreTicketResult.Succeed && omnivoreTicketResult.Object != null)
                        {
                            if (omnivoreTicketResult.Object.closed_at == null)
                            {
                                if (omnivoreTicketResult.Object.totals.due >= model.Amount)
                                {
                                    result = await _paymentService.AddAsync(LocationId, model.ToDomainPaymentModel());
                                }
                                else
                                {
                                    result.Error = "Omnivore ticket due lower than payment amount.";
                                }
                            }
                            else
                            {
                                result.Error = "Omnivore ticket closed.";
                            }
                        }
                        else
                        {
                            result.Error = omnivoreTicketResult.Error;
                        }
                    }
                    else
                    {
                        result.Error = identityResult.Error;
                    }
                }
                else
                {
                    result = await _paymentService.AddAsync(LocationId, model.ToDomainPaymentModel());
                }
            }
            else
            {
                result.Error = string.Join("| ", ModelState.Values.Select(v => !string.IsNullOrEmpty(v.Errors.FirstOrDefault()?.ErrorMessage) ? v.Errors.FirstOrDefault()?.ErrorMessage : v.Errors.FirstOrDefault()?.Exception?.Message));
            }

            return result.Succeed ? Ok(new CreateResultModel(result.ObjectId)) : (IHttpActionResult)BadRequest(result.Error);
        }

        /// <summary>
        /// Payment confirm
        /// </summary>
        /// <param name="paymentId">Payment id</param>
        /// <param name="transaction">Payment transaction model</param>
        /// <returns></returns>
        [HttpPost, Route("{paymentId}/confirm")]
        public async Task<IHttpActionResult> Confirm([FromUri]string paymentId, [FromBody]PaymentTransaction transaction)
        {
            var result = new Domain.Models.Api.v3.ResultModel(true);

            if (ModelState.IsValid)
            {
                var identityResult = _authService.GetIdentity(LocationId);
                if (identityResult.Succeed && identityResult.Object != null)
                {
                    result = await _paymentService.ConfirmAsync(paymentId, transaction?.ToDomainPaymentTransaction());
                    if (result.Succeed)
                    {
                        var paymentResult = await _paymentService.GetPaymentToThirdPartyPayment(paymentId);
                        if (paymentResult.Succeed && paymentResult.Object != null)
                        {
                            var omnivoreTicketResult = await _omnivoreService.GetTicketAsync(identityResult.Object.OmnivoreApiKey,
                                identityResult.Object.OmnivoreLocationId, paymentResult.Object.TicketId);
                            if (omnivoreTicketResult.Succeed && omnivoreTicketResult.Object != null)
                            {
                                if (omnivoreTicketResult.Object.closed_at == null)
                                {
                                    if (omnivoreTicketResult.Object.totals.due >= paymentResult.Object.Amount)
                                    {
                                        var sendPaymentResult = await _omnivoreService.SendThirdPartyPayment(identityResult.Object.OmnivoreApiKey, identityResult.Object.OmnivoreLocationId, paymentResult.Object);

                                        if (sendPaymentResult.Succeed)
                                        {
                                            var paymentResultContent = JsonConvert.SerializeObject(sendPaymentResult.Object);
                                            await _paymentService.UpdateStatusAsync(paymentId, Domain.Enums.PaymentStatusEnum.Paid, "Paid : " + paymentResultContent);
                                        }
                                        else
                                        {
                                            await _paymentService.UpdateStatusAsync(paymentId, Domain.Enums.PaymentStatusEnum.Confirmed, sendPaymentResult.Error);
                                        }
                                    }
                                    else
                                    {
                                        await _paymentService.UpdateStatusAsync(paymentId, Domain.Enums.PaymentStatusEnum.Cancelled, "Omnivore ticket due lower than payment amount.");
                                    }
                                }
                                else
                                {
                                    await _paymentService.UpdateStatusAsync(paymentId, Domain.Enums.PaymentStatusEnum.Cancelled, "Omnivore order closed.");
                                }
                            }
                            else
                            {
                                await _paymentService.UpdateMessageAsync(paymentId, omnivoreTicketResult.Error);
                            }
                        }
                        else
                        {
                            await _paymentService.UpdateMessageAsync(paymentId, paymentResult.Error);
                        }
                    }
                }
                else
                {
                    result = new Domain.Models.Api.v3.ResultModel(false, identityResult.Error);
                }
            }
            else
            {
                result.Succeed = false;
                result.Error = string.Join("| ", ModelState.Values.Select(v => !string.IsNullOrEmpty(v.Errors.FirstOrDefault()?.ErrorMessage) ? v.Errors.FirstOrDefault()?.ErrorMessage : v.Errors.FirstOrDefault()?.Exception?.Message));
            }

Onlinico.MiPoint.Web.Api/Controllers/PaymentsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using CsvHelper;
using Onlinico.MiPoint.Web.Api.Models.Web.Mapper;
using Onlinico.MiPoint.Web.Core.Interfaces;
using Onlinico.MiPoint.Web.Service.Interfaces.Web;

namespace Onlinico.MiPoint.Web.Api.Controllers
{
    public class PaymentsController : BaseController
    {
        private readonly IPaymentService _paymentService;

        public PaymentsController(IConfiguration configuration, IPaymentService paymentService) : base(configuration)
        {
            _paymentService = paymentService;
        }

        // GET: Payments
        public ActionResult Index(string locationId)
        {
            ViewBag.LocationId = locationId;
            return View();
        }

        public async Task<ActionResult> PaymentRows(string locationId, DateTime start, DateTime end, int timezoneOffset = 0)
        {
            var inverOffset = timezoneOffset * -1;


            var paymentResult = await _paymentService.GetAsync(locationId, start, end);
            
            return View(paymentResult.Object?.ToPaymentsViewModel());
        }

        public ActionResult PaymentRow(string paymentId)
        {
            return View();
        }

        public async Task<FileStreamResult> ExportPayments(string locationId, DateTime start, DateTime end)
        {
            var paymentsResult = await _paymentService.GetAsync(locationId, start, end);
            var result = WriteCsvToMemory(paymentsResult.Object);
            var memoryStream = new MemoryStream(result);
            return new FileStreamResult(memoryStream, "text/csv") { FileDownloadName = "export.csv" };
        }

        public byte[] WriteCsvToMemory(IEnumerable<Domain.Models.Web.PaymentModel> records)
        {
            using (var memoryStream = new MemoryStream())
            using (var streamWriter = new StreamWriter(memoryStream))
            using (var csvWriter = new CsvWriter(streamWriter))
            {
                csvWriter.WriteRecords(records);
                streamWriter.Flush();
                return memoryStream.ToArray();
            }
        }
    }
}

Onlinico.MiPoint.Web.Api/Views/Payments/Index.cshtml
@model List<Onlinico.MiPoint.Web.Api.Models.Web.PaymentViewModel>

<div>
    <header class="header">
        <h3>Payments</h3>
        <div style="float: right">
            <div class="action-btn-bar" style="display: inline-block; margin-right: 10px">
                <a id="download-payment-link" href="" download="payments.csv" class="action-btn action-btn-download" title="Download payments"></a>
            </div>
        </div>
    </header>
    <div style="margin-top: 30px;">
        <div class="container">
            <div class='col-md-1' style="padding-top: 12px; text-align: right;">
                <span>From</span>
            </div>
            <div class='col-md-4'>
                <div class="form-group">

                    <div class="input-group date" id="from-datetimepicker">
                        <input onkeydown="return false" id="startdate" value="@DateTime.UtcNow.Date" required type='text' class="form-control" style="max-width: 100%;" />
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
                </div>
            </div>
            <div class='col-md-1' style="padding-top: 12px; text-align: right;">
                <span>To</span>
            </div>
            <div class='col-md-4'>
                <div class="form-group">

                    <div class='input-group date' id="to-datetimepicker">
                        <input onkeydown="return false" id="enddate" value="@DateTime.UtcNow.Date.AddHours(24)" required type='text' class="form-control" style="max-width: 100%;" />
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
                </div>
            </div>
            <div class='col-md-2'>
                <input id="apply-btn" onclick="applyDatetime()" type="button" class="button save-button" value="Apply" style="width: 80px;" />
            </div>
        </div>
    </div>
    <div>
        <div id="container-payments" style="margin-top: 25px;">
            <div class="container">
                <table id="table-payments" class="table table-striped table-hover table-miPoint">
                    <thead>
                        <tr>
                            <th>OrderId</th>
                            <th>DeviceId</th>
                            <th>Created</th>
                            <th>Card type</th>
                            <th>Amount</th>
                            <th>Status</th>
                            <th>Type</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th colspan="4" style="text-align:right">Amount Total:</th>
                            <th colspan="3"></th>
                        </tr>
                    </tfoot>
                    <tbody id="tbody-merchants"></tbody>
                </table>
            </div>
        </div>

        <div id="container-empty-payments" class="center empty" style="display: none">
            <H4>payments empty.</H4>
        </div>
    </div>
</div>

<script type="text/javascript">

    var table;

    $(function () {
        var fromDate = $('#from-datetimepicker');
        var toDate = $('#to-datetimepicker');

        fromDate.datetimepicker();
        toDate.datetimepicker({
            //useCurrent: false //Important! See issue #1075
        });

        fromDate.on("dp.change", function (e) {

            toDate.data("DateTimePicker").minDate(e.date);
        });
        toDate.on("dp.change", function (e) {
            fromDate.data("DateTimePicker").maxDate(e.date);
        });

        table = $('#table-payments').DataTable({
            "pageLength": 10,
            "order": [[1, "asc"]],
            "columnDefs": [{
                "targets": 'no-sort',
                "orderable": false,
            }],
            "fnDrawCallback": function (oSettings) {
                var paginationButtons = $('.paginate_button');
                if (paginationButtons.length > 3) {
                    paginationButtons.show();
                } else {
                    paginationButtons.hide();
                }
            },
            "footerCallback": function (row, data, start, end, display) {
                
                var api = this.api(), data;

                // Remove the formatting to get integer data for summation
                var floatVal = function (i) {
                    if (typeof i === 'string') {
                        return parseFloat(i);
                    } else if (typeof i === 'number') {
                        return isNaN(i) ? 0 : i;
                    } else {
                        return 0;
                    }
                };

                // Total over all pages
                var total = api
                    .column(4, { "filter": "applied" })
                    .data()
                    .reduce(function (a, b) {
                        return floatVal(a) + floatVal(b);
                    }, 0);

                // Total over this page
                var pageTotal = api
                    .column(4, { page: 'current' })
                    .data()
                    .reduce(function (a, b) {
                        return floatVal(a) + floatVal(b);
                    }, 0);

                // Update footer
                $(api.column(4).footer()).html(
                    '$' + Math.round(pageTotal * 100) / 100 + ' ( $' + Math.round(total * 100) / 100 + ' total)'
                );
            }
        });

        getPayments();
        updateDownloadLink();
    });

    function updateDownloadLink() {
        var start = $('#startdate').val();
        var end = $('#enddate').val();
        var downloadUrl = '@Url.Action("ExportPayments", "Payments")' + '?locationId=' + '@ViewBag.LocationId' + "&start=" + encodeURIComponent(start) + "&end=" + encodeURIComponent(end);
        $("#download-payment-link").attr("href", downloadUrl);
    }

    function getPayments() {
        var start = $('#startdate').val();
        var end = $('#enddate').val();

        if (start !== "" && end !== "") {
            window.ShowOwerlay();

            $.get('@Url.Action("PaymentRows", "Payments")' + '?locationId=' + '@ViewBag.LocationId' + "&start=" + encodeURIComponent(start) + "&end=" + encodeURIComponent(end) + "&timezoneOffset=" + new Date().getTimezoneOffset() + '&random=' + window.getRandomInt(0, 99999), function (result) {
                table.clear().draw();
                table.rows.add($(result).filter("tr")).draw();
            }).done(function () {

            }).fail(function () {
                window.Notify('<strong>Error.</strong>', "Can't download locations. Please try again later.", 'danger');
            }).always(function () {
                window.HideOwerlay();
                $('#table-payments > tbody > tr').click(function () {
                    $(this).addClass('active').siblings().removeClass('active');
                });
            });
        } else {
            window.Notify('<strong>Message.</strong>', "Please enter 'From' and 'To' date.", 'info');
        }
    }

    function applyDatetime() {
        getPayments();
        updateDownloadLink();
    }
</script>

Onlinico.MiPoint.Web.Api/Views/Payments/PaymentRow.cshtml
@model Onlinico.MiPoint.Web.Api.Models.Web.PaymentViewModel
    
@{
    Layout = null;
}

@if (Model != null)
{
    <tr id="@Model.Id">
        <td>
            <div class="table-six-col-content hideOverflow">
                @Model.OrderId
            </div>
        </td>
        <td>
            <div class="table-six-col-content hideOverflow">
                @Model.DeviceId
            </div>
        </td>
        <td>
            <div class="table-six-col-content hideOverflow">
                @Model.Created
            </div>
        </td>
        <td>
            <div class="table-six-col-content hideOverflow">
                @Model.CardType
            </div>
        </td>
        <td>
            @Model.Amount
            @*<div class="table-six-col-content hideOverflow">
                @Model.Amount
            </div>*@
        </td>
        <td>
            <div class="table-six-col-content hideOverflow">
                @Model.Status
            </div>
        </td>
        <td>
            <div class="table-six-col-content hideOverflow">
                @Model.Type
            </div>
        </td>
    </tr>
}

Onlinico.MiPoint.Web.Api/Views/Payments/PaymentRows.cshtml
@model List<Onlinico.MiPoint.Web.Api.Models.Web.PaymentViewModel>
    
@{
    Layout = null;
}

@if (Model != null && Model.Any())
{
    foreach (var payment in Model)
    {
        Html.RenderPartial("PaymentRow", payment);
    }
}