Onlinico.MiPoint.Web.Api/Controllers/HistoryController.cs
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using Onlinico.MiPoint.Web.Api.Models.Web.Mapper;
using Onlinico.MiPoint.Web.Core.Interfaces;
using Onlinico.MiPoint.Web.Service.Interfaces.Web;

namespace Onlinico.MiPoint.Web.Api.Controllers
{
    /// <summary>
    /// History Controller
    /// </summary>
    public class HistoryController : BaseController
    {
        private readonly IHistoryService _historyService;

        /// <summary>
        /// Dependency Injection
        /// </summary>
        /// <param name="historyService">Inject history service</param>
        /// <param name="configuration">Inject configuration</param>
        public HistoryController(IHistoryService historyService, IConfiguration configuration) : base(configuration)
        {
            _historyService = historyService;
        }
        
        /// <summary>
        /// History root page
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Get history rows
        /// </summary>
        /// <param name="start">Start datetime</param>
        /// <param name="end">End datetime</param>
        /// <param name="timezoneOffset">Client offset</param>
        /// <returns></returns>
        public async Task<ActionResult> HistoryRows(DateTime start, DateTime end, int timezoneOffset = 0)
        {
            var inverOffset = timezoneOffset * -1;
            
            var histories = _historyService.Get(start.AddMinutes(timezoneOffset), end.AddMinutes(timezoneOffset));

            return View(histories.Object?.ToHistoryViewModels(inverOffset));
        }

        /// <summary>
        /// Get history content page
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult HistoryDetails(Guid id, int timezoneOffset = 0)
        {
            ViewBag.HistoryId = id;

            var inverOffset = timezoneOffset * -1;

            var content = _historyService.Get(id);

            return View(content.Object?.ToHistoryViewModel(inverOffset));
        }

        public ActionResult GetHistoryContent(Guid id)
        {
            var contentResuult = _historyService.GetContent(id);
            return Content(contentResuult.Object);
        }
    }
}

Onlinico.MiPoint.Web.Api/Views/History/HistoryDetails.cshtml
@model Onlinico.MiPoint.Web.Api.Models.Web.HistoryModel
<script src="~/Content/jsoneditor/jsoneditor.js"></script>
<link href="~/Content/jsoneditor/jsoneditor.css" rel="stylesheet" />

@if (Model != null)
{
    <div class="container" style="max-width: 900px">
        <h4>Request details</h4>

        <div style="margin-top: 30px; margin-bottom: 15px">
            @Html.Label("Secret", htmlAttributes: new { @class = "control-label col-md-2" })
            <div>
                @Html.EditorFor(model => model.LocationSecret, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LocationSecret, "", new { @class = "text-danger" })
            </div>
        </div>

        <div style="margin-bottom: 15px">
            @Html.Label("Device", htmlAttributes: new { @class = "control-label col-md-2" })
            <div>
                @Html.EditorFor(model => model.DeviceId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeviceId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div style="margin-bottom: 15px">
            @Html.LabelFor(model => model.Agent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div>
                @Html.EditorFor(model => model.Agent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Agent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div style="margin-bottom: 15px">
            @Html.LabelFor(model => model.Method, htmlAttributes: new { @class = "control-label col-md-2" })
            <div>
                @Html.EditorFor(model => model.Method, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Method, "", new { @class = "text-danger" })
            </div>
        </div>

        <div style="margin-bottom: 15px">
            @Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div>
                @Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div style="margin-bottom: 15px">
            @Html.LabelFor(model => model.Start, htmlAttributes: new { @class = "control-label col-md-2" })
            <div>
                @Html.EditorFor(model => model.Start, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Start, "", new { @class = "text-danger" })
            </div>
        </div>
        <div style="margin-bottom: 15px">
            @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div>
                @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
            </div>
        </div>
        <div style="margin-bottom: 15px">
            @Html.LabelFor(model => model.StatusCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div>
                @Html.EditorFor(model => model.StatusCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StatusCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div>
            <div style="margin-bottom: 15px">
                @Html.LabelFor(model => model.RequestHeaders, htmlAttributes: new { @class = "control-label col-md-2" })
                <div>
                    @Html.EditorFor(model => model.RequestHeaders, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.RequestHeaders, "", new { @class = "text-danger" })
                </div>
            </div>
            <div id="requestjsoneditor" style="">
                
            </div>
        </div>

        <div>
            <div style="margin-bottom: 15px; margin-top: 15px">
                @Html.LabelFor(model => model.ResponseHeaders, htmlAttributes: new { @class = "control-label col-md-2" })
                <div>
                    @Html.EditorFor(model => model.ResponseHeaders, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ResponseHeaders, "", new { @class = "text-danger" })
                </div>
            </div>
            <div id="responsejsoneditor" style="">
                
            </div>
        </div>

    </div>
}
else
{
    <div>
        <h2>Sorry, some error happened, please try again later.</h2>
    </div>
}

@section scripts {
    <script type="text/javascript">
        $(function () {
            var historyId = '@ViewBag.HistoryId';
            var requestcontainer = document.getElementById("requestjsoneditor");
            var responsecontainer = document.getElementById("responsejsoneditor");
            var options = {};
            var requesteditor = new JSONEditor(requestcontainer, options);
            var responseeditor = new JSONEditor(responsecontainer, options);

            try {
                requesteditor.set(JSON.parse(@Html.Raw(Json.Encode(Model.RequestContent))));
            } catch (e) {
                
            }

            try {
                responseeditor.set(JSON.parse(@Html.Raw(Json.Encode(Model.ResponseContent))));
            } catch (e) {
                
            }
            @*$.getJSON('@Url.Action("GetHistoryContent")' + "?id=" + historyId, function (result) {
                requesteditor.set(result);
            });*@

        })


    </script>

}
<style>
    input {
        max-width: 600px;
    }
</style>

Onlinico.MiPoint.Web.Api/Views/History/HistoryRow.cshtml
@model Onlinico.MiPoint.Web.Api.Models.Web.HistoryModel

@{
    Layout = null;
}

@if (Model != null)
{
    <tr id="@Model.Id">
        <td>
            <div class="table-six-col-content hideOverflow">
                @Model.LocationSecret
            </div>
        </td>
        <td>
            <div class="table-six-col-content hideOverflow">
                @Model.DeviceId
            </div>
        </td>
        <td>
            <div class="table-six-col-content hideOverflow">
                @Model.Method
            </div>
        </td>
        <td title="@Model.Url">
            <div class="table-six-col-content hideOverflow" style="max-width: 250px">
                @Model.Url
            </div>
        </td>
        <td class="start-datetime-col">
            <div class="table-six-col-content hideOverflow">
                @Model.Start.ToString("MM/dd/yyyy h:mm:ss tt")
            </div>
        </td>
        @*<td>
            <div class="table-six-col-content hideOverflow">
                @Model.Duration.ToString("g")
            </div>
        </td>*@
        <td>
            <div class="table-six-col-content hideOverflow">
                @Model.StatusCode
            </div>
        </td>
    </tr>
}

Onlinico.MiPoint.Web.Api/Views/History/HistoryRows.cshtml
@model List<Onlinico.MiPoint.Web.Api.Models.Web.HistoryModel>

@{
    Layout = null;
}

@if (Model != null && Model.Any())
{
    foreach (var history in Model)
    {
        <tr id="@history.Id">
            <td>
                <div class="table-six-col-content hideOverflow">
                    @history.LocationSecret
                </div>
            </td>
            <td>
                <div class="table-six-col-content hideOverflow">
                    @history.DeviceId
                </div>
            </td>
            <td>
                <div class="table-six-col-content hideOverflow">
                    @history.Method
                </div>
            </td>
            <td title="@history.Url">
                <div class="table-six-col-content hideOverflow" style="max-width: 250px">
                    @history.Url
                </div>
            </td>
            <td class="start-datetime-col">
                <div class="table-six-col-content hideOverflow">
                    @history.Start.ToString("MM/dd/yyyy h:mm:ss tt")
                </div>
            </td>
            @*<td>
                    <div class="table-six-col-content hideOverflow">
                        @Model.Duration.ToString("g")
                    </div>
                </td>*@
            <td>
                <div class="table-six-col-content hideOverflow">
                    @history.StatusCode
                </div>
            </td>
        </tr>
    }
}

Onlinico.MiPoint.Web.Api/Views/History/Index.cshtml
<script src="~/Scripts/moment.min.js"></script>

<div>
    <header class="header">
        <h3>Request history</h3>
    </header>

    <div style="margin-top: 35px;">
        <div class="container">
            <div class='col-md-1' style="padding-top: 12px; text-align: right;">
                <span>From</span>
            </div>
            <div class='col-md-4'>
                <div class="form-group">

                    <div class="input-group date" id="from-datetimepicker">
                        <input onkeydown="return false" id="startdate" value="@DateTime.UtcNow.Date" required type='text' class="form-control" style="max-width: 100%;" />
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
                </div>
            </div>
            <div class='col-md-1' style="padding-top: 12px; text-align: right;">
                <span>To</span>
            </div>
            <div class='col-md-4'>
                <div class="form-group">

                    <div class='input-group date' id="to-datetimepicker">
                        <input onkeydown="return false" id="enddate" value="@DateTime.UtcNow.Date.AddHours(24)" required type='text' class="form-control" style="max-width: 100%;" />
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
                </div>
            </div>
            <div class='col-md-2'>
                <input id="apply-btn" onclick="applyDatetime()" type="button" class="button save-button" value="Apply" style="width: 80px;" />
            </div>
        </div>
    </div>

    <div id="container-history" style="margin-top: 40px;">
        <div class="container">
            <table id="table-history" class="table table-striped table-hover table-miPoint">
                <thead>
                    <tr>
                        <th>Secret</th>
                        <th>Device</th>
                        <th>Method</th>
                        <th>Url</th>
                        <th>Start</th>
                        <th>Status Code</th>
                    </tr>
                </thead>
                <tbody id="tbody-history">
                </tbody>
            </table>
        </div>
    </div>


</div>


@section scripts {

    <script>
        var table;

        $(function () {

            var fromDate = $('#from-datetimepicker');
            var toDate = $('#to-datetimepicker');

            fromDate.datetimepicker();
            toDate.datetimepicker({
                //useCurrent: false //Important! See issue #1075
            });

            fromDate.on("dp.change", function (e) {

                toDate.data("DateTimePicker").minDate(e.date);
            });
            toDate.on("dp.change", function (e) {
                fromDate.data("DateTimePicker").maxDate(e.date);
            });

            table = $('#table-history').DataTable({
                "pageLength": 25,
                //"order": [[3, "desc"]],
                "aaSorting": [],
                "columnDefs": [
                    {
                        "targets": 'no-sort',
                        "orderable": false,
                    }
                ],
                "fnDrawCallback": function (oSettings) {
                    var paginationButtons = $('.paginate_button');
                    if (paginationButtons.length > 3) {
                        paginationButtons.show();
                    } else {
                        paginationButtons.hide();
                    }

                    var rows = $('tbody tr');
                    rows.unbind("dblclick");
                    rows.dblclick(function () {
                        var historyId = $(this).attr("id");
                        window.open('@Url.Action("HistoryDetails")' + "?id=" + historyId + "&timezoneOffset=" + new Date().getTimezoneOffset(), '_blank');
                    });
                }
            });

            getHistoryes();
        });

        function getHistoryes() {
            var start = $('#startdate').val();
            var end = $('#enddate').val();

            if (start !== "" && end !== "") {
                window.ShowOwerlay();

                $.get('@Url.Action("HistoryRows", "History")' + "?start=" + encodeURIComponent(start) + "&end=" + encodeURIComponent(end) + "&timezoneOffset=" + new Date().getTimezoneOffset() + '&random=' + window.getRandomInt(0, 99999), function (result) {
                    table.clear().draw();
                    table.rows.add($(result).filter("tr")).draw();
                }).done(function () {

                }).fail(function () {
                    window.Notify('<strong>Error.</strong>', "Can't download histories. Please try again later.", 'danger');
                }).always(function () {
                    window.HideOwerlay();
                    $('#table-history > tbody > tr').click(function () {
                        $(this).addClass('active').siblings().removeClass('active');
                    });
                });
            } else {
                window.Notify('<strong>Message.</strong>', "Please enter 'From' and 'To' date.", 'info');
            }
        }

        function applyDatetime() {
            getHistoryes();
        }
    </script>
}
<style>
    .center {
        margin: auto;
        width: 150px;
        align-content: center;
        padding: 10px;
    }
</style>