Onlinico.MiPoint.Web.Api/Controllers/Api/v1/LocationController.cs
using System.Web.Http;
using Onlinico.MiPoint.Web.Api.Models.Api.v1;
using Onlinico.MiPoint.Web.Api.Models.Api.v1.Mapper;
using Onlinico.MiPoint.Web.Core.Interfaces;
using Onlinico.MiPoint.Web.Service.Interfaces.Api.v1;

namespace Onlinico.MiPoint.Web.Api.Controllers.Api.v1
{
    /// <summary>
    /// Application settings controller
    /// </summary>
    [Attributes.Authorize, RoutePrefix("api/locations")]
    public class LocationController : BaseController
    {
        private readonly ILocationService _locationService;

        private readonly IConfiguration _configuration;

        /// <summary>
        /// Location controller constructor
        /// </summary>
        public LocationController(Logger.Interfaces.ILogger logger, ILocationService locationService, IConfiguration configuration) : base(logger)
        {
            _locationService = locationService;
            _configuration = configuration;
        }

        /// <summary>
        /// Get current application settings
        /// </summary>
        /// <returns></returns>
        [HttpGet, Route("current/settings")]
        public LocationSettingsModel Get()
        {
            var locationSettings = _locationService.GetSettings(Request.Properties[_configuration.Secret].ToString());
            var result = locationSettings?.ToApiLocationSettingsModel();
            return result;
        }
    }
}

Onlinico.MiPoint.Web.Api/Controllers/Api/v2/LocationController.cs
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Results;
using Onlinico.MiPoint.Web.Api.Models.Api.v2;
using Onlinico.MiPoint.Web.Api.Models.Api.v2.Mapper;
using Onlinico.MiPoint.Web.Core.Interfaces;
using Onlinico.MiPoint.Web.Service.Interfaces.Api.v2;

namespace Onlinico.MiPoint.Web.Api.Controllers.Api.v2
{
    /// <summary>
    /// Application settings controller
    /// </summary>
    [Attributes.Authorize, RoutePrefix("api/v2/locations")]
    public class LocationController : BaseController
    {
        private readonly ILocationService _locationService;

        private readonly IConfiguration _configuration;

        /// <summary>
        /// Location controller constructor
        /// </summary>
        public LocationController(Logger.Interfaces.ILogger logger, ILocationService locationService, IConfiguration configuration) : base(logger)
        {
            _locationService = locationService;
            _configuration = configuration;
        }

        /// <summary>
        /// Get location info
        /// </summary>
        /// <returns></returns>
        [HttpGet, Route("current")]
        public async Task<LocationModel> Get()
        {
            var result = await _locationService.GetAsync(Request.Properties[_configuration.Secret].ToString());

            return result.Object?.ToApiLocationModel();
        }

        /// <summary>
        /// Get current application settings
        /// </summary>
        /// <returns></returns>
        [HttpGet, Route("current/settings")]
        public IHttpActionResult /*LocationSettingsModel*/ GetSettings()
        {
            var locationSettings = _locationService.GetSettings(Request.Properties[_configuration.Secret].ToString());

            if (locationSettings != null)
            {
                return Ok(locationSettings.ToApiLocationSettingsModel());
            }
            else
            {
                return BadRequest();
            }
        }

        /// <summary>
        /// Get employee by employee login
        /// </summary>
        /// <param name="login">employee login</param>
        /// <returns></returns>
        [HttpGet, Route("current/employees/{login}")]
        public async Task<IHttpActionResult> GetEmployee(string login)
        {
            var locationId = Request.Properties[_configuration.Secret].ToString();

            var result = await _locationService.GetEmployeeAsync(locationId, login);

            return result.Succeed ? Ok(result.Object?.ToEmployeeModel()) : (IHttpActionResult)BadRequest(result.Error);
        }
    }
}

Onlinico.MiPoint.Web.Api/Controllers/Api/v3/LocationController.cs
using System.Net;
using System.Net.Http;
using System.ServiceModel.Channels;
using System.Threading.Tasks;
using System.Web;
using System.Web.Http;
using System.Web.Http.Description;
using System.Web.Http.Results;
using Onlinico.MiPoint.Web.Api.Models.Api.v3;
using Onlinico.MiPoint.Web.Api.Models.Api.v3.Enums;
using Onlinico.MiPoint.Web.Api.Models.Api.v3.Mapper;
using Onlinico.MiPoint.Web.Core.Interfaces;
using Onlinico.MiPoint.Web.Service.Interfaces.Api.v3;

namespace Onlinico.MiPoint.Web.Api.Controllers.Api.v3
{
    /// <summary>
    /// Application settings controller
    /// </summary>
    [Attributes.Authorize, RoutePrefix("api/v3/locations")]
    public class LocationController : BaseController
    {
        private readonly ILocationService _locationService;

        private readonly IConfiguration _configuration;

        /// <summary>
        /// Location controller constructor
        /// </summary>
        public LocationController(Logger.Interfaces.ILogger logger, ILocationService locationService, IConfiguration configuration) : base(logger)
        {
            _locationService = locationService;
            _configuration = configuration;
        }

        
        /// <summary>
        /// Get current application settings
        /// </summary>
        /// <returns></returns>
        [HttpGet, Route("current/settings")]
        public LocationSettingsModel GetSettings()
        {
            var locationSettingsResult = _locationService.GetSettings(Request.Properties[_configuration.Secret].ToString());

            if (locationSettingsResult.Succeed && locationSettingsResult.Object != null)
            {
                return locationSettingsResult.Object.ToApiLocationSettingsModel();
            }
            else
            {
                var responce = new HttpResponseMessage(HttpStatusCode.BadRequest)
                {
                    Content = new StringContent(locationSettingsResult.Error)
                };
                throw new HttpResponseException(responce);
            }
        }

        /// <summary>
        /// Get employee by employee login
        /// </summary>
        /// <param name="login">employee login</param>
        /// <returns></returns>
        [HttpGet, Route("current/employees/{login}")]
        [ResponseType(typeof(EmployeeModel))]
        public async Task<IHttpActionResult> GetEmployee(string login)
        {
            var locationId = Request.Properties[_configuration.Secret].ToString();

            var result = await _locationService.GetEmployeeAsync(locationId, login);

            return result.Succeed ? Ok(result.Object?.ToEmployeeModel()) : (IHttpActionResult)BadRequest(result.Error);
        }

        /// <summary>
        /// Agent Heart Beat
        /// </summary>
        /// <param name="lub"></param>
        /// <returns></returns>
        [HttpPost, Route("current/heartbeat")]
        public async Task<DubModel> HeartBeatAsync(LubModel lub)
        {
            var result = new Domain.Models.Api.v3.ResultModel(true);

            var clientIp = GetClientIp();

            if (!string.IsNullOrEmpty(clientIp))
            {
                return new DubModel() {UpdateUrl = clientIp};
            }
            else
            {
                var responce = new HttpResponseMessage(HttpStatusCode.BadRequest)
                {
                    Content = new StringContent("Can't get client ip address.")
                };
                throw new HttpResponseException(responce);
            }
        }

        private string GetClientIp(HttpRequestMessage request = null)
        {
            request = request ?? Request;

            if (request.Properties.ContainsKey("MS_HttpContext"))
            {
                return ((HttpContextWrapper)request.Properties["MS_HttpContext"]).Request.UserHostAddress;
            }
            else if (request.Properties.ContainsKey(RemoteEndpointMessageProperty.Name))
            {
                RemoteEndpointMessageProperty prop = (RemoteEndpointMessageProperty)request.Properties[RemoteEndpointMessageProperty.Name];
                return prop.Address;
            }
            else if (HttpContext.Current != null)
            {
                return HttpContext.Current.Request.UserHostAddress;
            }
            else
            {
                return null;
            }
        }

        protected override void Dispose(bool disposing)
        {
            _locationService.Dispose();
            base.Dispose(disposing);
        }
    }
}

Onlinico.MiPoint.Web.Api/Controllers/Api/v4/LocationController.cs
using System;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.ServiceModel.Channels;
using System.Threading.Tasks;
using System.Web;
using System.Web.Http;
using System.Web.Http.Description;
using System.Web.Http.Results;
using Microsoft.AspNet.SignalR;
using Onlinico.MiPoint.Web.Api.Hubs;
using Onlinico.MiPoint.Web.Api.Models.Api.v4;
using Onlinico.MiPoint.Web.Api.Models.Api.v4.Enums;
using Onlinico.MiPoint.Web.Api.Models.Api.v4.Mapper;
using Onlinico.MiPoint.Web.Core.Interfaces;
using Onlinico.MiPoint.Web.Service.Interfaces.Api.v4;
using Swashbuckle.Swagger.Annotations;

namespace Onlinico.MiPoint.Web.Api.Controllers.Api.v4
{
    ///// <summary>
    ///// Application settings controller
    ///// </summary>
    //[Attributes.Authorize, RoutePrefix("api/v4/locations")]
    //public class LocationController : BaseController
    //{
    //    private readonly ILocationService _locationService;

    //    /// <summary>
    //    /// Location controller constructor
    //    /// </summary>
    //    public LocationController(Logger.Interfaces.ILogger logger, ILocationService locationService, IConfiguration configuration) : base(logger, configuration)
    //    {
    //        _locationService = locationService;
    //    }


    //    /// <summary>
    //    /// Get location settings
    //    /// </summary>
    //    /// <returns></returns>
    //    [HttpGet]
    //    [Route("current/settings")]
    //    [SwaggerResponse(HttpStatusCode.OK, Type = typeof(LocationSettingsModel))]
    //    [SwaggerResponse(HttpStatusCode.NoContent)]
    //    [SwaggerResponse(HttpStatusCode.BadRequest, Type = typeof(ApiExceptionModel))]
    //    public async Task<IHttpActionResult> GetSettings()
    //    {
    //        //var connectorHubContext = GlobalHost.ConnectionManager.GetHubContext<ConnectorHub>();
    //        //connectorHubContext.Clients.All.getLogByDate(DateTime.UtcNow.AddDays(-1).Date);
            
    //        var locationSettingsResult = await _locationService.GetSettingsAsync(LocationId);

    //        if (locationSettingsResult.Succeed && locationSettingsResult.Object != null)
    //        {
    //            return Ok(locationSettingsResult.Object.ToApiLocationSettingsModel());
    //        }
    //        else
    //        {
    //            throw CreateApiException(locationSettingsResult.Error);
    //        }
    //    }
        
    //    protected override void Dispose(bool disposing)
    //    {
    //        _locationService.Dispose();
    //        base.Dispose(disposing);
    //    }
    //}
}

Onlinico.MiPoint.Web.Api/Views/Location/AddLocations.cshtml
@model List<Onlinico.MiPoint.Web.Api.Models.Web.SelectedItem<Onlinico.MiPoint.Web.Api.Models.Web.LocationModel>>
@{
    Layout = null;
}

<div class="modal-dialog">

    @using (Ajax.BeginForm("AddLocations", "Location", new AjaxOptions { OnBegin = "AddLocationsBegin", OnSuccess = "AddLocationsSuccess", OnFailure = "AddLocationsFailre", OnComplete = "AddLocationsComplete" }, new { id = "add-locations-form" }))
    {
        <input name="merchantId" type="hidden" value="@ViewBag.MerchantId" />
                <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Add locations</h4>
            </div>
            <div class="modal-body">
                <div>
                    <div>
                        <label>Locations</label>
                    </div>
                    <select id="user-merchants-multiselect" name="identifiers" multiple="multiple">
                        @if (Model != null && Model.Any())
                        {
                            for (var i = 0; i < Model.Count; i++)
                            {
                                <option name="identifiers[@i]" value="@Model[i].Item.Identifier" @(Model[i].Selected ? "selected" : "")>@Model[i].Item.Name</option>
                            }
                        }
                    </select>
                </div>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-default button save-button">Add</button>
                <button type="button" class="btn btn-default button back-button" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    }
</div>

<script type="text/javascript">
    $(function () {
        $('#user-merchants-multiselect').multiselect({
            includeSelectAllOption: true,
            enableFiltering: true
        });

        $("#add-locations-form").attr("action", $("#add-locations-form").attr("action") + "&timeOffset=" + new Date().getTimezoneOffset());
    });

    function AddLocationsBegin() {
        window.ShowOwerlay();
    }

    function AddLocationsSuccess() {
        $('#location-form-container').modal('hide');

        setTimeout(
            function () {
                window.ReloadLocations("Success.", "Add locations success", 'success');
        }, 500);
    }

    function AddLocationsFailre(result) {
        window.Notify('<strong>Error.</strong>', "Can't add locations", 'danger');
    }

    function AddLocationsComplete() {
        window.HideOwerlay();
    }
</script>

Onlinico.MiPoint.Web.Api/Views/Location/Emty.cshtml
@{
    Layout = null;
}

Onlinico.MiPoint.Web.Api/Views/Location/Index.cshtml
@{
    Html.RenderAction("Locations", "Location", new { merchantId = ViewBag.MerchantId });
}

Onlinico.MiPoint.Web.Api/Views/Location/LocationRow.cshtml
@model Onlinico.MiPoint.Web.Api.Models.Web.LocationModel

@if (Model != null)
{
    <tr id="@Model.Id" fingerprint="@Model.AgentFingerprint">
        <td>
            <div>
                <a onclick="EditLocationSettings('@Model.Id', '@Model.IsOffline.ToString()')" class="table-icon settings-location-icon" title="Configure location settings"></a>
                <a onclick="EditLocationMappingScheme('@Model.Id')" class="table-icon mapping-scheme-location-icon" title="Edit location mapping scheme"></a>
                @if (!Model.IsOffline)
                {
                    <a onclick="ConfirmSyncLocation('@Model.Id')" class="table-icon row-sync-icon" title="Sync location with Omnivore"></a>
                }

                @if (ViewBag.IsAdmin ?? true)
                {
                    <a onclick="ConfirmRemoveLocation('@Model.Id')" class="table-icon row-remove-icon" title="Remove location"></a>
                }

                <div class="dropdown @(!string.IsNullOrEmpty(Model.AgentFingerprint)  ? "" : "hidden-item")">
                    <button onclick="toggleDropdown('@(Model.Id + "-btn-toggle")')" class="dropbtn table-icon client-settings-icon" title="Agent actions"></button>
                </div>
                <div id="@(Model.Id + "-btn-toggle")" class="dropdown-content" style="position: absolute">
                    <a class="online @(Model.IsAgentActive || Model.IsVicarActive ? "" : "hidden-item")" onclick="RestartAgent('@Model.Id')">Agent restart</a>
                    <a onclick="RemoveAgentKey('@Model.Id')">Clear agent key</a>
                    <a class="online @(Model.IsAgentActive || Model.IsVicarActive ? "" : "hidden-item")" onclick="GetAgentLog('@Model.Id')">Get log</a>
                    <a class="online @(Model.IsAgentActive || Model.IsVicarActive ? "" : "hidden-item")" onclick="UpdateAgent('@Model.Id')">Agent update</a>
                </div>

            </div>
        </td>
        <td>
            <div class="table-six-col-content hideOverflow">
                @*<div class="location-indicator @(!string.IsNullOrEmpty(Model.AgentFingerprint) ? Model.IsActive ? "location-indicator-online" : "location-indicator-offline" : string.Empty)"></div>*@

                <div class="location-indicator location-indicator-online @(Model.IsAgentActive ? string.Empty : "hidden-item")"></div>
                <div class="location-indicator location-indicator-degraded @(Model.IsVicarActive ? string.Empty : "hidden-item")"></div>
                <div class="location-indicator location-indicator-offline @(!string.IsNullOrEmpty(Model.AgentFingerprint) ? string.Empty : "hidden-item")"></div>

                <span class="@(Model.IsConfigured || Model.IsOffline ? null : "notConfigured")" style="margin-left: 20px;">
                    @( Model.IsConfigured || Model.IsOffline ? Model.Id : "Need to configure")
                </span>

            </div>
        </td>
        <td>
            <div class="table-six-col-content hideOverflow">
                @Model.Identifier
            </div>
        </td>
        <td>
            <div class="table-six-col-content hideOverflow">
                @Model.Name
            </div>
        </td>
        <td>
            <div class="table-six-col-content hideOverflow">
                @Model.Owner
            </div>
        </td>
        <td>
            <div class="table-six-col-content hideOverflow">
                @Model.PosType
            </div>
        </td>
    </tr>
}

Onlinico.MiPoint.Web.Api/Views/Location/LocationRows.cshtml
@model List<Onlinico.MiPoint.Web.Api.Models.Web.LocationModel>
@{
    Layout = null;
}
@if (Model != null && Model.Any())
{
    foreach (var location in Model)
    {
        Html.RenderPartial("LocationRow", location);
    }
}

Onlinico.MiPoint.Web.Api/Views/Location/LogRequestForm.cshtml
@model Onlinico.MiPoint.Web.Api.Models.Web.LogRequestModel
@{
    Layout = null;
}
<div class="modal-dialog">
    <div id="basket" style="display: none"></div>
    @using (Ajax.BeginForm("LogRequestForm", new AjaxOptions { OnSuccess = "SendLogRequestSuccess", OnBegin = "SendLogRequestBegin", OnFailure = "SendLogRequestFailre", OnComplete = "SendLogRequestComplete" }))
    {
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Log request form</h4>
            </div>
            <div class="modal-body">
                <div>
                    <input name="LocationId" type="hidden" value="@Model.LocationId" />
                    <div>
                        <label>@Html.RadioButtonFor(m => m.IsAgentLog, true) Agent log</label>

                        <label> @Html.RadioButtonFor(m => m.IsAgentLog, false) Client log</label>
                    </div>
                    <div>
                        <div>
                            <label>Log by date</label>
                        </div>

                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-12">
                                    <input id="log-date-picker" name="LogDate" required type="text" onkeydown="return false" value="@Model.LogDate" class="inputs" placeholder="Log date" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-default button save-button">Send</button>
                <button type="button" class="btn btn-default button back-button" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    }

    <script type="text/javascript">
        $(function () {
            $("#log-date-picker").datetimepicker({
                format: 'MM/DD/YYYY'
            });
        });

        function SendLogRequestBegin(result) {
            window.ShowOwerlay();
        }

        function SendLogRequestSuccess(result) {
            $('#location-form-container').modal('hide');

            setTimeout(
                function () {
                    window.ReloadLocations("Success.", "Send log request success", 'success');
                }, 500);
        }

        function SendLogRequestFailre(result) {
            window.Notify('<strong>Error.</strong>', "Can't send log request", 'danger');
        }

        function SendLogRequestComplete(result) {
            window.HideOwerlay();
        }
    </script>

</div>

Onlinico.MiPoint.Web.Api/Views/Location/MappingScheme.cshtml
@model Onlinico.MiPoint.Web.Api.Models.Web.MappingSchemeModel

@{
    Layout = null;
}

<div class="modal-dialog">
    @*<div id="basket" style="display: none"></div>*@
    @using (Ajax.BeginForm("MappingScheme", "Location", new { Area = "" }, new AjaxOptions { OnSuccess = "SaveMappingSchemeSuccess", OnBegin = "SaveMappingSchemeBegin", OnFailure = "SaveMappingSchemeFailre", OnComplete = "SaveMappingSchemeComplete" }, new { id = "location-mapping-scheme-form" }))
    {
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Location mapping scheme</h4>
            </div>
            <div class="modal-body">
                <div>
                    <input name="model.LocationId" type="hidden" value="@Model.LocationId" />
                    <div>
                        <h3>Employees scheme</h3>
                        <div class="container">
                            <div class="col-md-5"><label>MiPoint model</label></div>
                            <div class="col-md-2"></div>
                            <div class="col-md-5"><label>Omnivore model</label></div>

                            @foreach (var employee in Model.EmployeeModelProperties.Select((value, i) => new { i, value }))
                            {
                                var selectedEmployyeList = Model.EmployeeModelProperties.Select(p => new SelectListItem
                                {
                                    Text = p.Text,
                                    Value = p.Value,
                                    Selected = Model.Employees != null
                                        ? Model.Employees.ContainsKey(employee.value.Value) && Model.Employees[employee.value.Value] == p.Value
                                        : employee.value.Value == p.Value,
                                });

                                <div class="col-md-5" style="padding: 0;">
                                    <div style="margin-top: 5px">
                                        <input name="model.Employees[@employee.i].Key" readonly="readonly" type="text" class="form-control" value="@employee.value.Value" />
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div style="margin: 16px auto auto auto; width: 30px; height: 20px">
                                        <img style="width: 30px; height: 20px;" src="/Content/Icons/double-arrow-left-icon.jpg" />
                                    </div>
                                </div>
                                <div class="col-md-5" style="padding: 0;">
                                    <div style="margin-top: 5px">
                                        @Html.DropDownList($"model.Employees[{employee.i}].Value", selectedEmployyeList, new { @class = "form-control" })
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                    <br />
                    <div>
                        <h3>Table scheme</h3>
                        <div class="container">
                            <div class="col-md-5"><label>MiPoint model</label></div>
                            <div class="col-md-2"></div>
                            <div class="col-md-5"><label>Omnivore model</label></div>

                            @foreach (var table in Model.TableModelProperties.Select((value, i) => new { i, value }))
                            {
                                var selectedEmployyeList = Model.TableModelProperties.Select(p => new SelectListItem
                                {
                                    Text = p.Text,
                                    Value = p.Value,
                                    Selected = Model.Tables != null
                                        ? Model.Tables.ContainsKey(table.value.Value) && Model.Tables[table.value.Value] == p.Value
                                        : table.value.Value == p.Value,
                                });

                                <div class="col-md-5" style="padding: 0;">
                                    <div style="margin-top: 5px">
                                        <input name="model.Tables[@table.i].Key" readonly="readonly" type="text" class="form-control" value="@table.value.Value" />
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div style="margin: 16px auto auto auto; width: 30px; height: 20px">
                                        <img style="width: 30px; height: 20px;" src="/Content/Icons/double-arrow-left-icon.jpg" />
                                    </div>
                                </div>
                                <div class="col-md-5" style="padding: 0;">
                                    <div style="margin-top: 5px">
                                        @Html.DropDownList($"model.Tables[{table.i}].Value", selectedEmployyeList, new { @class = "form-control" })
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-default button save-button">Save</button>
                <button type="button" class="btn btn-default button back-button" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    }

</div>

<script type="text/javascript">
    $(function () {

    });

    function SaveMappingSchemeBegin() {
        if (!confirm('Change default schema mapping can badly affect to work client device. Do you want to save changes?'))
            return false;

        $(".save-button").attr('disabled', 'disabled');
        window.ShowOwerlay();
    }

    function SaveMappingSchemeSuccess(result) {
        $('#location-form-container').modal('hide');
        window.Notify('<strong>Success.</strong>', "Save mapping scheme success", 'success');
    }

    function SaveMappingSchemeFailre(result) {
        window.Notify('<strong>Error.</strong>', "Can't save mapping scheme", 'danger');
    }

    function SaveMappingSchemeComplete(result) {
        $(".save-button").removeAttr('disabled');
        window.HideOwerlay();
    }
</script>

Onlinico.MiPoint.Web.Api/Views/Location/NewOfflineLocation.cshtml
@model Onlinico.MiPoint.Web.Api.Models.Web.OfflineLocationModel
@{
    Layout = null;
}

<div class="modal-dialog" style="width: 650px">
    <!-- Modal content-->
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Add offline location</h4>
        </div>

        @using (Ajax.BeginForm("NewOfflineLocation", "Location", new AjaxOptions { OnSuccess = "AddOfflineLocationSuccess", OnBegin = "AddOfflineLocationBegin", OnFailure = "AddOfflineLocationFailre", OnComplete = "AddOfflineLocationComplete" }, new { id = "offline-location-form" }))
            {
            <div class="modal-body">
                <div>
                    <div>
                        <input name="model.MerchantId" type="hidden" value="@Model.MerchantId" />

                        <input name="model.Name" required type="text" class="inputs modal-dialog-input" maxlength="250" placeholder="Name" />

                        <input name="model.Owner" required type="text" class="inputs modal-dialog-input" maxlength="250" placeholder="Owner" />

                        <input name="model.PosType" required type="text" value="micros3700" class="inputs modal-dialog-input" maxlength="250" placeholder="PosType" />

                        <input name="model.Phone" type="tel" pattern="(\+?\d[- .]*){7,13}" title="International, national or local telephone number" class="inputs modal-dialog-input" placeholder="Phone number" />

                        <input name="model.Address" type="text" class="inputs modal-dialog-input" maxlength="250" placeholder="Address" />

                        <input name="model.AddressFull" type="text" class="inputs modal-dialog-input" maxlength="250" placeholder="Full Address" />
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <input class="btn btn-default button save-button" type="submit" value="Add" />
                <button type="button" class="btn btn-default button back-button" data-dismiss="modal">Cancel</button>
            </div>
        }
    </div>
</div>

<script type="text/javascript">
    $(function () {
        $("#offline-location-form").attr("action", $("#offline-location-form").attr("action") + "&timeOffset=" + new Date().getTimezoneOffset());
    });

    function AddOfflineLocationBegin() {
        $(".add-button").attr('disabled', 'disabled');
        window.ShowOwerlay();
    }

    function AddOfflineLocationSuccess(result) {
        $('#location-form-container').modal('hide');

        setTimeout(
            function () {
                window.ReloadLocations("Success.", "Add offline location.", 'success');
            }, 500);

    }

    function AddOfflineLocationFailre(result) {
        window.Notify('<strong>Error.</strong>', result.statusText, 'danger');
    }

    function AddOfflineLocationComplete(result) {
        $(".add-button").removeAttr('disabled');
        window.HideOwerlay();
    }
</script>